(() => {
  "use strict";
  const deck = [];
  const add = (title, section, guide, html, notes = "", layout = "") => deck.push({title, section, guide, html, notes, layout});
  const asset = (path) => `../assets/${path}`;
  const h = (eyebrow, title) => `<div class="eyebrow">${eyebrow}</div><h1>${title}</h1>`;
  const media = (path, alt, caption = "", cls = "") => `<figure class="evidence-media ${cls}"><img src="${asset(path)}" alt="${alt}"><figcaption>${caption}</figcaption></figure>`;
  const screenPanel = (path, alt, caption, points) => `<div class="screen-panel">${media(path,alt,caption)}<div class="screen-points">${points.map((p,i)=>`<div><b>${String(i+1).padStart(2,"0")}</b><span>${p}</span></div>`).join("")}</div></div>`;
  const wizardPanel = () => `<div class="screen-panel"><figure class="evidence-media"><div class="wizard-shot"><img src="${asset("sengpt/20260929/agent-prompt.png")}" alt="실제 SenGPT 에이전트 Prompt 입력 영역과 오른쪽 요술봉 버튼"><span class="wizard-marker" aria-hidden="true"></span></div><figcaption>실제 Prompt 화면 · 동그라미가 오른쪽 요술봉 버튼</figcaption></figure><div class="screen-points"><div><b>01</b><span>에이전트의 역할이나 목적을 간단히 적습니다.</span></div><div><b>02</b><span>오른쪽 요술봉으로 Prompt 작성 도움을 받습니다.</span></div><div><b>03</b><span>제안된 Prompt의 역할·출력 형식을 확인합니다.</span></div><div><b>04</b><span>자료 범위와 제약을 교사가 수정·확정합니다.</span></div></div></div>`;
  const source = (text) => `<span class="source-line">${text}</span>`;
  const callout = (text) => `<p class="takeaway">${text}</p>`;
  const row = (items) => `<div class="plain-row">${items.map(x => `<div>${x}</div>`).join("")}</div>`;
  function guided(path, alt, caption, steps) {
    return `<div class="guided-layout"><div class="guided-screen"><figure class="evidence-media"><div class="guided-image-wrap"><img src="${asset(path)}" alt="${alt}">
      ${steps.map((s,i)=>`<span class="step-pin" data-step="${i+1}" style="left:${s[2]}%;top:${s[3]}%">${i+1}</span>`).join("")}</div><figcaption>${caption}</figcaption></figure></div>
      <div class="guided-explain"><div class="step-status">Space / 클릭으로 순서 확인 <b data-step-count>0 / ${steps.length}</b></div>
      ${steps.map((s,i)=>`<div class="reveal-note" data-step="${i+1}"><b>${String(i+1).padStart(2,"0")} ${s[0]}</b><p>${s[1]}</p></div>`).join("")}</div></div>`;
  }
  const s = (a,b,x=35,y=55) => [a,b,x,y];
  const toolNames = [
    ["타이머","시간 재기와 집중","timer"],["현재시간","현재 시각 확인","clock"],["랜덤뽑기","입력 항목 가운데 무작위 선택","random"],
    ["돌림판","시각적 선택","wheel"],["점수판","팀 점수 관리","score"],["모둠만들기","학생 명단 섞기","groups"],
    ["사다리타기","역할·순서 정하기","ladder"],["주사위","간단한 확률 활동","dice"],["뽑기레이스","레이스로 당첨자 뽑기","race"],["QR 만들기","주소를 QR 코드로","qr"]
  ];
  const publishers = [
    ["동아","두클래스","duclass"],["미래엔","엠티처","mteacher"],["천재교육","T셀파","tcellpa"],["금성","티칭허브","teachinghub"],
    ["YBM","Y클라우드","ycloud"],["비상교육","비바샘","vivasam"],["지학사","티솔루션","tsolution"],["아이스크림","아이스크림","iscream"]
  ];
  const officialAgents = [
    ["연수·성장","official-training-1.png"],["수업·평가·연구","official-teaching-1.png"],
    ["학생지원·생활","official-student-1.png"],["안전·보호","official-safety-1.png"],
    ["계약·인사","official-contract-1.png"],["민원·기관","official-civil-1.png"],["공모전 당선작","official-award-1.png"]
  ];
  const officialGallery = (items) => `<div class="official-agent-gallery">${items.map(([name,file])=>`<button type="button" data-modal-src="${asset(`sengpt/20260929/${file}`)}" data-modal-title="서울시교육청 에이전트 · ${name}" aria-label="${name} 실제 화면 열기"><img src="${asset(`sengpt/20260929/${file}`)}" alt="${name}의 실제 에이전트 목록"><strong>${name}</strong></button>`).join("")}</div>`;

  // A. 입장과 전체 흐름
  add("계정·연수자료 QR","시작","G01",`${h("입장 전 대기 화면","계정과 연수 자료")}<div class="qr-pair">
    <figure><img src="${asset("hanyoung/account-qr.png")}" alt="SEN 및 연수 계정 안내 QR"><figcaption>SEN·연수 계정 확인</figcaption></figure>
    <figure><img src="${asset("hanyoung/padlet-qr.png")}" alt="한영고 연수 Padlet QR"><figcaption>연수 자료·교재</figcaption></figure></div>
    <p class="direct-address">직접 주소 <strong>senedu.kr</strong> · <strong>bit.ly/26한영고</strong></p>
    ${callout("학교 계정으로 로그인 상태를 확인하고, 교재를 별도 탭에 열어 둡니다.")}`,"입장 대기 중 표시한다. QR은 화면에서 충분히 크게 유지한다. 참가자 교재에도 직접 주소가 있다.","qr-slide");
  add("SEN스쿨 × 구글 클래스룸(Education Plus)","시작","G01",`<div class="eyebrow">한영고등학교 교원 연수</div><h1>SEN스쿨 × 구글 클래스룸(Education Plus)</h1><p class="subtitle">Gemini Notebook과 Classroom Gemini로 수업 준비하기</p><p class="meta">2026. 9. 29. · 한영고등학교</p><div class="brand-row"><img src="${asset("brand/institute-logo-from-pptx.png")}" alt="서울특별시교육청교육연구정보원 공식 로고"><img src="${asset("logos/google-for-education.png")}" alt="Google for Education 공식 로고"></div>`,"공식 제목·부제를 그대로 사용한다. 두 로고는 제공된 공식 원본 자산이다.","cover");
  add("강사 소개","시작","G01",`${h("강사 소개","강사 소개")}<div class="speaker"><strong>이진선</strong><span>종로산업정보학교 AI컴퓨터과</span></div><div class="speaker-career"><div>2024–2026 AI·에듀테크 선도교사</div><div>2025–2026 중부 중등 AI디지털기반 역량강화 연수 기획단</div><div>2026 SEN스쿨 지원단·컨설팅단</div><div>2026 서울시교육청 제2호 교사개발자</div></div>`,"이름과 소속을 먼저 소개한다. 경력은 청중이 읽을 수 있는 크기로 표시한다.");
  add("오늘의 전체 흐름","시작","G01",`${h("오늘의 연수","오늘의 전체 흐름")}<div class="journey">${["SEN스쿨","Google Education","한영고 사례","Gemini Notebook","Classroom Gemini","SenGPT"].map((v,i)=>`<div><b>${String(i+1).padStart(2,"0")}</b><span>${v}</span></div>`).join("")}</div>${callout("현장 필수 실습은 Classroom Gemini의 ‘일반적인 오개념 바로잡기’입니다.")}`,"이 화면에서는 Source→Prompt→Verify→Output을 아직 설명하지 않는다. 여섯 구간의 전체 지도를 먼저 보여준다.");

  // C. SEN스쿨
  add("SEN스쿨 홈","SEN스쿨","G02",`${h("SEN스쿨","교사 화면의 출발점")}${media("captured/20260928/sen-home-current.png","2026년 9월 SEN스쿨 교사 홈 실제 화면","교사 계정에서 확인한 현재 홈 · 2026.9.28.","large")}`,"홈의 클래스·도구모음·ToolKit 진입점을 짚는다. 이미 확보한 같은 날 실제 UI 캡처를 사용한다.","evidence-slide");
  add("SEN스쿨 전체 기능","SEN스쿨","G02",`${h("SEN스쿨","교사용 매뉴얼의 여섯 장")}<div class="chapter-map">${["클래스 만들기","내 클래스 & 꾸러미","클래스 관리","우리반 관리","마이페이지","수업지원 ToolKit & 출판사"].map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join("")}</div>${source("출처: SEN스쿨 주요 개편 및 추가 교사용 매뉴얼, 2026.9.17.")}`,"공식 매뉴얼 41쪽을 그대로 복사하지 않고 여섯 장의 기능 구조를 먼저 보여준다.");
  add("2026학년도 2학기 주요 개편","SEN스쿨","G03",`${h("SEN스쿨","2026학년도 2학기 주요 개편")}<div class="reform-grid"><div><b>교사가 사용하는 기능</b><p>클래스 개설 간소화<br>학생 비밀번호 변경 권한 확대<br>Classroom 학생 초대<br>웨일클래스 학생 명단 동기화<br>교과서 출판사 8종 연계</p></div><div><b>학교관리자 범위</b><p>조직도 자동 동기화<br>담임 배정 절차 간소화</p></div></div>${source("출처: SEN스쿨 주요 개편 및 추가 기능 안내, 2026.9.17.")}`,"교사 기능 5개와 관리자 범위 2개를 한눈에 구분한다.");
  add("교사와 학교관리자 역할","SEN스쿨","G03",`${h("SEN스쿨","교사와 학교관리자의 연결")}<div class="role-map"><div><strong>교사</strong><span>클래스 개설</span><span>학생 비밀번호</span><span>LMS·수업도구</span><span>학생 초대</span></div><div class="role-connector">수업 운영을<br>함께 뒷받침</div><div><strong>학교관리자</strong><span>조직도 자동 동기화</span><span>담임 배정 절차 간소화</span></div></div>`,"교사 계정에서 관리자 설정을 직접 조작하는 화면으로 오해하지 않게 설명한다.");
  add("클래스 만들기 안내","SEN스쿨","G04",`${h("클래스 만들기","시작 전 안내 확인")}${guided("captured/20260928/sen-class-create-01-guidance.png","실제 클래스 만들기 안내 화면","교사 계정 실제 화면 · 2026.9.28.",[s("안내 읽기","클래스 개설 안내를 먼저 확인합니다.",50,43),s("확인 체크","안내를 모두 숙지했다는 체크박스를 선택합니다.",20.7,56.2),s("다음","오른쪽 아래 다음 버튼을 누릅니다.",79.1,65.7)])}`,"현재 교사 계정에서 확인한 안내 화면이다. 저장이나 학생 배정은 실행하지 않는다.","guided-slide");
  add("클래스 만들기 방식","SEN스쿨","G04",`${h("클래스 만들기","직접 만들기와 CSV 업로드")}${guided("captured/20260928/sen-class-create-02-method.png","실제 클래스 만들기 방식 선택","교사 계정 실제 화면 · 2026.9.28.",[s("직접 만들기","왼쪽 선택 라디오를 누르면 클래스 하나를 직접 입력합니다.",20.8,46.9),s("파일 업로드","오른쪽 선택 라디오를 누르면 CSV·XLSX로 여러 클래스를 만듭니다.",52.7,46.9),s("다음","오른쪽 아래 다음 버튼을 누릅니다.",79.1,56.8)])}`,"공식 매뉴얼 5쪽과 현재 UI의 두 방식을 연결한다.","guided-slide");
  add("클래스 기본정보","SEN스쿨","G04",`${h("클래스 만들기","클래스명과 소개")}${guided("captured/20260928/sen-class-create-03-basic.png","실제 클래스 기본정보 입력 화면","교사 계정 실제 화면 · 2026.9.28.",[s("클래스명","30자까지 입력할 수 있습니다.",48,39),s("클래스 소개","선택 입력이며 200자까지 가능합니다.",50,59),s("다음","정보 입력 뒤 학생 배정 단계로 이동합니다.",76,80)])}`,"공식 매뉴얼 6쪽. 실제 화면은 저장 전 상태다.","guided-slide");
  add("내 클래스와 수업꾸러미","SEN스쿨","G05",`${h("SEN스쿨 기능 구조","내 클래스에서 수업꾸러미까지")}<div class="process-map"><div><b>내 클래스</b><span>우리반 현황 · 교과 클래스 목록</span></div><div><b>클래스 홈</b><span>자료 · 과제 · 학생 · LMS</span></div><div><b>수업꾸러미</b><span>등록 · 학습맵 · 성취기준 · 보충자료</span></div></div>${source("기능·순서 근거: SEN스쿨 공식 교사용 매뉴얼 10–18쪽")}`,"현재 교사 계정에서 개별 클래스 화면이 열리지 않아 UI를 표시하지 않는다. 참가자 교재 G05–G06에 세부 메뉴와 공식 근거를 남긴다.");
  add("클래스·우리반 관리 범위","SEN스쿨","G07",`${h("SEN스쿨 기능 구조","클래스 관리와 우리반 관리")}<div class="process-map"><div><b>클래스 기본정보</b><span>담당교사 · 부교사 · 이름 · 소개</span></div><div><b>학생 관리</b><span>명단 · 비밀번호 변경 진입 · 배정</span></div><div><b>우리반 관리</b><span>학생정보 불러오기 · 학생 관리</span></div></div>${callout("연수에서는 실제 학생의 비밀번호·배정 상태를 변경하지 않습니다.")}${source("기능·순서 근거: SEN스쿨 공식 교사용 매뉴얼 20–29쪽")}`,"교재 G07–G08에 실제 조작 전까지의 상세 절차를 둔다. 이것은 현재 UI 캡처가 아니라 공식 매뉴얼 기반 기능 구조다.");
  add("마이페이지 설정 범위","SEN스쿨","G09",`${h("SEN스쿨 기능 구조","마이페이지에서 바꾸는 화면")}<div class="process-map"><div><b>메인화면</b><span>기본 표시 정보</span></div><div><b>클래스와 우리반</b><span>표시 항목 · 클래스 순서</span></div><div><b>수업도구</b><span>LMS · 도구 · 교과서 출판사</span></div></div>${source("기능·순서 근거: SEN스쿨 공식 교사용 매뉴얼 30–38쪽")}`,"교재 G09에는 메인화면·클래스·우리반·순서 설정의 세부 절차를 남긴다. 이어서 실제 수업도구 설정 화면을 보여준다.");
  add("수업도구 설정 상단","SEN스쿨","G10",`${h("마이페이지","LMS와 수업도구 설정")}${guided("captured/20260928/sen-tools-settings-top.png","실제 수업도구 설정 상단 화면","교사 계정 실제 화면 · 2026.9.28.",[s("LMS","연결할 LMS를 설정합니다.",47,30),s("수업도구","자주 쓰는 수업도구를 켜거나 끕니다.",47,51)])}`,"이 캡처에는 출판사 설정 영역이 보이지 않는다. 다음 화면에서 실제 스크롤 후 출판사 영역을 별도로 보여준다.","guided-slide");
  add("수업지원 ToolKit 10종","SEN스쿨","G10",`${h("수업지원 ToolKit","열 가지 교사용 도구")}<p class="interact-hint">카드에 마우스를 올리거나 Tab으로 선택해 설명을 보고, 클릭·Enter·탭으로 실제 화면을 엽니다.</p><div class="tool-grid">${toolNames.map(([name,desc,file],i)=>`<button class="flip-card media-card" type="button" data-modal-src="${asset(`toolkit/20260929/${file}.png`)}" data-modal-title="${name} · 실제 초기 화면" aria-label="${name} 실제 화면 열기"><img src="${asset(`toolkit/20260929/${file}.png`)}" alt=""><b>${String(i+1).padStart(2,"0")}</b><strong>${name}</strong><span>${desc}</span></button>`).join("")}</div>${source("실제 ToolKit 화면 · 2026.9.29. / 공식 매뉴얼 39–40쪽")}`,"실제 학생 정보를 입력하지 않은 열 도구의 초기 화면이다. 클릭하면 해당 실제 캡처를 확대한다.","interactive-slide");
  add("교과서 출판사 설정","SEN스쿨","G11",`${h("마이페이지","SEN스쿨 × 교과서 출판사")}${media("captured/20260928/sen-publisher-settings.png","실제 교과서 출판사 설정 화면","교사 계정 실제 화면 · 2026.9.28.","large")}`,"이 화면은 수업도구 설정 안의 교과서 출판사 영역이다. LMS나 웨일클래스와 혼동하지 않는다.","evidence-slide");
  add("주요 출판사 연계","SEN스쿨","G11",`${h("교과서 출판사","8개 출판사와 연결 서비스")}<p class="interact-hint">카드의 서비스 표식은 실제 SEN 설정 화면에서 잘랐습니다. 클릭하면 원본 설정 화면을 확대합니다.</p><div class="publisher-grid">${publishers.map(([name,service,file])=>`<button class="flip-card publisher-card" type="button" data-modal-src="${asset("captured/20260928/sen-publisher-settings.png")}" data-modal-title="${name} · ${service} 실제 설정 화면" aria-label="${name} ${service} 설정 화면 열기"><img src="${asset(`publishers/${file}.png`)}" alt="${service} 실제 화면 표식"><strong>${name}</strong><span>${service} · 최초 연결 시 인증 확인</span></button>`).join("")}</div>${source("실제 SEN 교사 계정 화면 · 2026.9.28. / 공식 매뉴얼 41쪽")}`,"공식 매뉴얼 41쪽의 8개 매핑을 실제 SEN 설정 화면의 서비스 표식과 연결한다. 아이스크림은 출판사와 서비스 이름이 같다.","interactive-slide");

  // D. Google Education
  add("Google Education 도구 지도","Google Education","G12",`${h("Google Education","수업 준비와 운영의 도구 지도")}<div class="edu-map"><div><b>Workspace</b><span>Docs · Sheets · Slides · Forms · Drive</span></div><div><b>Classroom</b><span>수업·과제의 공간</span></div><div><b>Gemini 기능</b><span>자료 탐색과 교사용 생성</span></div><div><b>Meet</b><span>실시간 협업</span></div><div><b>관리·분석</b><span>학교 계정과 사용 현황 관리</span></div></div>`,"전체 도구 지도를 2분 내 보여준다. 상세 기능보다 오늘 쓸 두 Gemini 도구의 위치가 중요하다.");
  add("Education Plus","Google Education","G12",`${h("Google Education","Education Plus에서 보는 범위")}<div class="edu-plus"><strong>수업</strong><span>Classroom과 학습 도구</span><strong>협업</strong><span>Workspace · Meet</span><strong>운영</strong><span>관리·보안·분석 기능</span></div>${callout("실제 제공 기능은 학교 설정과 계정 권한에서 확인합니다.")}`,"Education Plus의 세부 기능을 길게 설명하지 않는다. 기관 설정에 따른 차이를 말한다.");
  add("Gemini Notebook과 Classroom Gemini","Google Education","G12",`${h("오늘 사용하는 두 도구","근거 탐색과 수업 초안")}<div class="compare-tools"><div><strong>Gemini Notebook</strong><p>교사가 고른 자료를 Source로 모읍니다.<br>여러 문서에 같은 질문을 던집니다.<br>인용을 눌러 원문과 답변을 비교합니다.<br>Studio에서 다른 형식으로 재구성합니다.</p></div><div><strong>Classroom Gemini</strong><p>Classroom 안의 교사용 생성 도구입니다.<br>수업계획·퀴즈·기준표·오개념 등 시작점을 제공합니다.<br>간단한 입력으로 초안을 만듭니다.<br>교사가 학교·교과·학생 맥락에 맞게 고칩니다.</p></div></div>`,"두 도구의 역할을 처음 접하는 교사도 이해할 수 있도록 설명한다. Notebook의 인용 확인과 Classroom 초안 수정을 구별한다.");

  // E. 학교 사례
  add("한영고 콰렌스","한영고 사례","G13",`${h("한영고 사례","콰렌스 콜로키움")}<p class="lead-text">학생이 Big Question을 제안하고 자료를 탐구해 제안서와 발표·질의응답으로 발전시키는 QBL 기반 탐구 프로그램</p><div class="two-stage"><div><b>1단계</b><strong>Big Question · 제안서</strong></div><div><b>2단계</b><strong>발표 · 질의응답</strong></div></div>${source("출처: 한영고 2026 학교교육계획, 인쇄 82–83쪽")}`,"콰렌스와 교과 수행평가를 동일한 제도로 단정하지 않는다. 학교 내부 PDF 전체는 참가자 배포물에 넣지 않는다.");
  add("Big Question","한영고 사례","G13",`${h("한영고 사례","이번 연수의 Big Question")}<div class="big-question">생성형 AI 시대에 학생의 능력을<br>우리는 무엇으로 평가해야 하는가?</div>${callout("자료마다 어떤 근거를 제시하는지 살펴봅니다.")}`,"확정된 질문을 읽고 Notebook 시연의 초점을 제시한다.","big-question-slide");

  // F. Gemini Notebook 강사 시연
  add("Gemini Notebook","Gemini Notebook","G14",`${h("Gemini Notebook","교사가 고른 자료로 묻고 확인")}${row(["Source<br><small>직접 고른 자료</small>","Chat<br><small>질문과 인용</small>","Studio<br><small>결과 형식</small>"])}${callout("이번 본편은 강사 시연입니다. 참가자 자율 실습은 교재 19절에 남겨 둡니다.")}`,"강사용 8-Source Notebook을 시연한다. 참가자 편집 공간으로 쓰지 않는다.");
  add("Notebook을 쓰는 상황","Gemini Notebook","G14",`${h("Gemini Notebook","자료를 함께 읽어야 할 때")}<div class="usecases"><p>서로 다른 정책·연구 자료의 관점을 비교할 때</p><p>답변의 한 문장을 원문에서 확인할 때</p><p>같은 근거를 인포그래픽·마인드맵으로 다시 볼 때</p></div>`,"자료를 선택하고 원문과 비교하는 작업에 초점을 둔다.");
  add("일반 Gemini와 Notebook","Gemini Notebook","G14",`${h("Gemini Notebook","자료 범위의 차이")}<div class="compare-tools"><div><strong>일반 Gemini</strong><p>넓은 질문에서 출발합니다.<br>답변이 어떤 자료에 기대는지 별도로 확인해야 합니다.</p></div><div><strong>Gemini Notebook</strong><p>교사가 등록한 Source를 중심으로 답합니다.<br>연결된 인용을 눌러 원문을 열 수 있습니다.</p></div></div>${callout("Source를 등록해도 답변의 정확성이 자동으로 보장되지는 않습니다.")}`,"개념 비교다. 일반 Gemini의 모든 기능을 단순화한 공식 제품 비교표로 제시하지 않는다.");
  add("Notebook 전체 화면","Gemini Notebook","G14",`${h("Gemini Notebook","전체 화면")}${media("captured/20260928/notebook-studio-overview.png","Source·Chat·Studio가 보이는 실제 Notebook 화면","교육계정 실제 화면 · 2026.9.28.","large dark")}`,"왼쪽 Source, 가운데 Chat, 오른쪽 Studio를 눈으로 찾는다.","evidence-slide");
  add("Source · Chat · Studio","Gemini Notebook","G14",`${h("Gemini Notebook","세 영역의 역할")}${guided("captured/20260928/notebook-studio-overview.png","Gemini Notebook 실제 세 영역","교육계정 실제 화면 · 2026.9.28.",[s("Source","선택한 자료와 본문을 확인합니다.",14,48),s("Chat","질문·답변·인용을 읽습니다.",50,50),s("Studio","자료를 다른 형식으로 구성합니다.",84,49)])}`,"왼쪽·가운데·오른쪽을 순서대로 짚는다.","guided-slide");
  add("실제 8 Source 1–4","Gemini Notebook","G15",`${h("강사 시연 자료","실제 8 Source · 학교와 국내 자료")}<div class="source-list"><div><b>01</b><strong>한영고 2026 학교교육계획</strong><span>콰렌스 운영 맥락</span></div><div><b>02</b><strong>교육부 2025 수행평가 AI 활용 관리 방안 보도자료</strong><span>정책 방향</span></div><div><b>03</b><strong>서울특별시교육청 2026 고등학교 학업성적관리 시행지침</strong><span>규정과 예시 구분</span></div><div><b>04</b><strong>KERIS 운영 학교생활기록부 종합지원포털 2026 과제형 수행평가 Q&A</strong><span>공개 질의응답</span></div></div>`,"내부 자료는 제목·역할만 소개한다. 교재에는 공개 자료 원문 링크를 제공한다.");
  add("실제 8 Source 5–8","Gemini Notebook","G15",`${h("강사 시연 자료","실제 8 Source · 연구와 안전")}<div class="source-list"><div><b>05</b><strong>Bastani 외, Generative AI Without Guardrails Can Harm Learning</strong><span>특정 고교 수학 실험</span></div><div><b>06</b><strong>OECD Digital Education Outlook 2026</strong><span>수행과 학습의 차이</span></div><div><b>07</b><strong>OECD–EU Empowering Learners for the Age of AI</strong><span>AI Literacy Framework</span></div><div><b>08</b><strong>개인정보보호위원회 2026 생성형 AI 서비스 이용자 개인정보 보호 가이드</strong><span>입력·설정·권한 안전</span></div></div>`,"Bastani 연구를 모든 교과로 일반화하지 않는다. 개인정보 가이드를 평가 배점 규정으로 읽지 않는다.");
  add("Studio 전체 버튼","Gemini Notebook","G18",`${h("Gemini Notebook","Studio에서 결과 형식 선택")}${media("crops/notebook-studio-panel.png","실제 Notebook Studio 오른쪽 패널을 확대한 화면","교육계정 실제 화면의 오른쪽 패널 확대 · 2026.9.28.","large dark")}${callout("실제 결과가 있는 네 가지: 인포그래픽 · 마인드맵 · 슬라이드 자료 · 퀴즈")}`,"Studio 오른쪽 패널의 실제 버튼을 크게 보여 준다. 다음 네 결과는 저장된 실제 산출물이다.","evidence-slide");
  add("맞춤 채팅 설정","Gemini Notebook","G14",`${h("Gemini Notebook","맞춤 설정")}${media("hanyoung/notebook-settings.png","실제 Notebook 맞춤 채팅 설정","기존 실제 교육계정 화면","large dark")}${callout("답변 형식 설정은 원문 검증을 대신하지 않습니다.")}`,"역할·스타일·길이 설정을 확인한다. 설정 후에도 오류가 있었다.","evidence-slide");
  add("Source → Prompt → Verify → Output","Gemini Notebook","G16",`${h("Gemini Notebook 시연","Source → Prompt → Verify → Output")}<div class="flow-four"><div><b>Source</b><span>자료 선택</span></div><div><b>Prompt</b><span>질문 범위</span></div><div><b>Verify</b><span>인용·원문 비교</span></div><div><b>Output</b><span>형식 변환</span></div></div>${callout("최종 사용 여부는 교사가 판단합니다.")}`,"이 개념은 Notebook 화면과 Source 설명 뒤에 나온다.");
  add("강사 실제 질문","Gemini Notebook","G16",`${h("Gemini Notebook 시연","실제로 입력한 질문")}<div class="screen-panel">${media("captured/20260928/notebook-prompt-filled.png","공개 Q&A 한 Source에 입력한 Prompt 실제 화면","공개 Q&A 1-Source 실습 재현 · 8-Source 시연과 별개")}<div class="screen-points"><b>입력 위치 확대</b><img class="screen-inline-crop" src="${asset("crops/notebook-prompt-entry.png")}" alt="실제 Notebook Prompt 입력 영역 확대"><div><span>강사 8-Source 질문은 학습 증거 세 가지, 직접 근거와 교사용 제안의 분리, 예시·권고·의무의 구별을 요청합니다.</span></div></div></div>`,"원본과 실제 Prompt 입력 위치의 확대를 함께 보여 준다. 이 이미지는 공개 Q&A 한 Source 재현이며 강사 8 Source 시연 화면과 혼동하지 않는다.","screen-panel-slide");
  add("답변과 인용","Gemini Notebook","G16",`${h("공개 Q&A 1-Source 재현","답변 문장 → 인용")}${media("captured/20260928/notebook-answer-citations.png","공개 Q&A 한 자료의 답변과 인용 실제 화면","공개 KERIS Q&A 1-Source 검증 재현 · 2026.9.28.","large dark")}`,"이것은 8 Source 강사 Notebook이 아니라 공개 Q&A 한 자료로 재현한 인용 확인 장면이다.","evidence-slide");
  add("인용 클릭","Gemini Notebook","G16",`${h("공개 Q&A 1-Source 재현","인용 클릭 → 원문 열기")}${media("captured/20260928/notebook-citation-open.png","공개 Q&A 인용을 열어 원문과 답변을 본 실제 화면","공개 KERIS Q&A 1-Source 검증 재현 · 2026.9.28.","large dark")}`,"답변 주장과 연결된 원문을 나란히 확인한다. 역사적 오류 두 건의 당시 캡처는 아니다.","evidence-slide");
  add("원문 대조","Gemini Notebook","G16",`${h("Gemini Notebook 시연","원문이 주장한 범위")}<div class="verify-row"><div><b>답변 한 문장</b><p>무엇을 주장하나요?</p></div><div><b>연결된 Source</b><p>올바른 문서인가요?</p></div><div><b>원문 표현</b><p>가능·조건·예시가 남아 있나요?</p></div></div>${callout("비교 결과를 유지·수정·보류 중 하나로 판단합니다.")}`,"강사가 인용 원문을 여는 화면과 함께 세 가지 질문을 소리 내어 확인한다.");
  add("오류 1: 표현 강화","Gemini Notebook","G17",`${h("실제 오류 1","가능 표현이 의무 규정으로 강화")}<div class="evidence-compare">${media("captured/20260928/notebook-citation-open.png","인용을 열어 원문을 대조하는 실제 Notebook 화면","검증 방법 재현 화면 · 당시 오류 캡처 아님")}<div class="evidence-compare-notes"><b>실제 검증 기록</b><p>원문 예시: “채점에서 제외될 수 있음”</p><p>AI 답변: “제외하도록 규정”</p><strong>가능·예시가 의무로 강화됐는지 확인</strong></div></div>${source("출처: 서울교육청 2026 고등학교 학업성적관리 시행지침과 실제 검증 기록")}`,"당시 답변 화면은 보존되지 않았다. 왼쪽은 같은 인용 대조 과정을 보여 주는 별도 실제 화면이며, 오른쪽은 기록의 두 문장이다.","evidence-compare-slide");
  add("오류 2: 잘못된 Source 연결","Gemini Notebook","G17",`${h("실제 오류 2","연구 주장에 학교 자료가 연결")}<div class="evidence-compare">${media("captured/20260928/notebook-citation-open.png","실제 Notebook 인용을 열어 Source 이름을 확인하는 화면","검증 방법 재현 화면 · 당시 오류 캡처 아님")}<div class="evidence-compare-notes"><b>실제 검증 기록</b><p>확인할 주장: Bastani 외 고교 수학 연구 결과</p><p>열린 Source: 한영고 학교교육계획의 다른 부분</p><strong>번호뿐 아니라 문서명과 원문을 확인</strong></div></div>`,"당시 오류 UI는 보존되지 않았다. 왼쪽 화면은 인용을 여는 실제 동작의 재현이며 해당 오류가 표시된 화면은 아니다.","evidence-compare-slide");
  add("인포그래픽 실제 결과","Gemini Notebook","G18",`${h("Studio 결과","인포그래픽")}${media("hanyoung/studio-infographic.png","실제 생성된 학생평가 인포그래픽","Gemini Notebook 실제 생성 결과","large dark")}`,"이 구간에서 가장 많은 설명 시간을 쓴다. 원본을 먼저 보고 다음 화면에서 표현을 검토한다.","evidence-slide");
  add("인포그래픽 표현 검토","Gemini Notebook","G18",`${h("Studio 결과","‘자료의 관점’과 ‘교사용 제안’ 구별")}<div class="evidence-compare">${media("crops/studio-infographic-source-vs-proposal.png","원본 인포그래픽의 주황색과 보라색 영역 실제 확대","원본 결과의 오른쪽 두 칸 확대 · 원본 미수정")}<div class="evidence-compare-notes"><b>이 화면에서 확인할 곳</b><p>주황색: AI 제시 근거와 출처의 신뢰성 검증</p><p>보라색: 평가의 최종 판단은 교사가 주도</p><strong>아래 ‘교사용 적용 제안’을 공식 공통 규정으로 읽지 않습니다.</strong></div></div>`,"실제 보이는 자료의 관점과 교사용 적용 제안의 층위를 구별한다.","evidence-compare-slide");
  add("수정 마인드맵","Gemini Notebook","G18",`${h("Studio 결과","수정 마인드맵")}${media("hanyoung/studio-mindmap-zoom.png","실제 수정된 학생평가 마인드맵","Gemini Notebook 실제 수정 결과","large dark")}`,"수정본의 중심 질문과 주요 가지를 읽는다.","evidence-slide");
  add("선택 Studio 슬라이드","Gemini Notebook","G18",`${h("Studio 결과","선택 슬라이드 · 국내 지침")}${media("hanyoung/studio-slide-3.png","실제 생성된 Studio 슬라이드 세 번째 화면","Gemini Notebook 실제 생성 결과","large dark")}`,"학생 유의사항의 예시·가능 표현을 일률적 금지로 강화하지 않는다.","evidence-slide");
  add("선택 Studio 슬라이드: 과정","Gemini Notebook","G18",`${h("Studio 결과","결과와 과정을 함께")}${media("hanyoung/studio-slide-5.png","실제 생성된 Studio 슬라이드 다섯 번째 화면","Gemini Notebook 실제 생성 결과","large dark")}`,"결과물을 지우지 않고 과정과 함께 읽는다.","evidence-slide");
  add("검증된 퀴즈","Gemini Notebook","G18",`${h("Studio 결과","검증된 퀴즈 1번")}${screenPanel("hanyoung/studio-quiz-q1-complete.png","A부터 D까지와 정답 C 및 근거가 보이는 실제 퀴즈 화면","실제 Gemini Notebook 퀴즈 1/5 · 정답 C",["질문: 수행평가에서 AI 활용을 어떻게 관리할까?","정답 C: 교사가 학생 활동을 직접 관찰하고 독자적 사고가 반영되도록 합니다.","5문항 가운데 1번만 원문과 대조했습니다."])}`,"사용자가 제공한 실제 전체 화면이다. C가 정답으로 표시되고 근거 설명이 보인다. 나머지 4문항을 검증됐다고 말하지 않는다.","screen-panel-slide");
  add("퀴즈 1번 선택지 확대","Gemini Notebook","G18",`${h("Studio 결과","퀴즈 1번 · 선택지와 근거 확대")}<div class="quiz-zoom">${media("crops/studio-quiz-q1-ab.png","실제 퀴즈 1번 질문과 A B 선택지 확대","원본의 질문 · A · B 확대")}${media("crops/studio-quiz-q1-cd.png","실제 퀴즈 1번 C D 선택지와 정답 근거 확대","원본의 C 정답·근거 · D 확대")}</div>${callout("정답 C의 근거를 원문과 대조했습니다. 다른 4문항은 검증 범위 밖입니다.")}`,"사용자 제공 실제 화면에서 선택지 영역만 잘랐다. A부터 D까지 화면에서 읽을 수 있다.","pair-slide");

  // G. Classroom Gemini 필수 실습
  add("Classroom Gemini","Classroom Gemini","G20",`${h("Classroom Gemini","교사용 생성 도구로 진입")}${media("hanyoung/classroom-gemini.png","실제 Classroom Gemini 도구 메뉴","교육계정 실제 화면","large")}`,"Classroom Gemini가 수업계획·퀴즈·기준표·오개념 등 시작점을 제공한다는 점을 짚는다.","evidence-slide");
  add("일반적인 오개념 바로잡기","Classroom Gemini","G21",`${h("이번 현장 필수 실습","일반적인 오개념 바로잡기")}${media("crops/classroom-tool-grid.png","실제 Classroom Gemini 도구 목록에서 일반적인 오개념 바로잡기 선택","교육계정 실제 화면에서 도구 영역 확대","large")}${callout("수업 계획 개요 작성은 교재의 다른 기능 예시에만 둡니다.")}`,"오늘 참가자가 직접 조작할 도구의 메뉴를 실제 화면에서 찾는다.","evidence-slide");
  add("학년과 주제 입력","Classroom Gemini","G21",`${h("실제 테스트","고등학교 1학년 + 주제")}${media("crops/classroom-input-form.png","일반적인 오개념 바로잡기 학년과 주제 입력 양식 실제 화면","실제 입력 양식의 저장된 빈 화면 · 입력값은 교재에 별도 제시","large")}${callout("학년: 고등학교 1학년 · 주제: 생성형 AI 활용과 평가")}`,"저장된 캡처는 빈 입력 양식이다. 값이 이미 입력된 화면인 것처럼 말하지 않는다. 실제 입력 문구는 교재 G21에 있다.","evidence-slide");
  add("첫 생성 결과","Classroom Gemini","G21",`${h("실제 테스트","첫 생성 결과")}${media("captured/classroom-misconception-result-20260928.png","실제 첫 결과의 보존된 화면","교육계정 실제 테스트 · 첫 두 항목이 보이는 캡처","large")}`,"보존된 캡처에는 첫 두 항목만 보인다. 콰렌스 오류가 이 이미지에 보이는 것처럼 말하지 않는다.","evidence-slide");
  add("콰렌스 의미 확장 오류","Classroom Gemini","G21",`${h("첫 결과의 오류","콰렌스를 다른 제도로 읽음")}<div class="error-compare"><div><b>첫 결과 기록</b><strong>“윤리적·학술적 진위 검증 과정(콰렌스)”</strong></div><div><b>학교교육계획의 맥락</b><strong>Big Question에서 제안·발표로 이어지는 학생 탐구</strong></div></div>${callout("학교 고유명사는 교사가 원문으로 의미를 확인합니다.")}`,"3번 항목의 실제 오류 기록이다. 전용 캡처는 없다.");
  add("Classroom 정정 요청","Classroom Gemini","G21",`${h("2026.9.29 새 검증","정정 요청을 다시 입력했습니다")}${media("captured/20260929/classroom/new-correction-form.png","정정 문구를 넣은 실제 Classroom Gemini 학년·주제 입력 화면","실제 정정 입력 화면의 확대 · 주제 칸은 첫 부분만 표시","large")}${callout("정정 입력 전문은 참가자 교재 G21에서 확인합니다.")}${source("과거 대화의 복원 화면이 아닌 2026.9.29 새 실행")}`,"당시 정정 전용 기록은 찾지 못해 새 테스트를 실행했다. 입력창은 가로 한 줄이므로 전문이 화면에 보이지 않는다. 전문은 교재 G21과 사용자가 제공한 Docs 내보내기 파일에 있다. 화면의 '1학년학년' 중복은 서비스에서 자동 생성한 제목 그대로다.","evidence-slide");
  add("Classroom 새 검증 결과","Classroom Gemini","G21",`${h("2026.9.29 새 검증","정정 후 새 결과")}${media("captured/20260929/classroom/new-result-1-zoom.png","새로 생성한 오개념 첫 항목, 학생 열린 질문과 교사용 안내가 구분된 실제 화면","실제 결과 첫 항목 확대 · 영어 소제목과 한국어 제안이 함께 표시","large")}${callout("활동 제안은 초안입니다. 교사가 학교 맥락에 맞게 고릅니다.")}${source("사용자가 제공한 2026.9.29 실제 결과 · 과거 정정 결과와 구별")}`,"새 결과 실제 화면이다. Big Question과 콰렌스 학생 탐구가 등장하고 '학생을 위한 열린 질문'과 '교사용 안내 및 제안'이 구분된다. 영어 소제목이 남고 제안 중 일부는 학교 공식 기준이 아니므로 채택·수정 여부를 교사가 결정한다.","evidence-slide");
  add("교사의 최종 표현","Classroom Gemini","G21",`${h("실제 테스트","교사가 마지막 문장을 수정")}<div class="prompt-hero">학생의 설명 가능한 수정 과정과<br>최종 결과물을 함께 살펴본다.<br>콰렌스 탐구 발표와 교과 성취기준 평가는<br>목적을 구별한다.</div>`,"학교 공식 정책이나 일률적 배점을 새로 쓰지 않는다.");
  add("필수 실습 1: 진입","Classroom Gemini","G21",`${h("참가자 필수 실습 1","Classroom Gemini 열기")}${media("hanyoung/classroom-gemini.png","Classroom Gemini 진입 실제 화면","참가자 교재 21절에서 직접 주소 확인","large")}`,"Classroom의 Gemini 메뉴로 들어간다. 연결이 안 되면 교재 화면으로 관찰형 학습을 한다.","evidence-slide");
  add("필수 실습 2: 도구 선택","Classroom Gemini","G21",`${h("참가자 필수 실습 2","일반적인 오개념 바로잡기")}${media("crops/classroom-tool-grid.png","실제 Classroom Gemini 도구 목록","실제 화면 확대 · ‘일반적인 오개념 바로잡기’ 선택","large")}`,"도구 명칭을 정확히 찾는다.","evidence-slide");
  add("필수 실습 3: 입력","Classroom Gemini","G21",`${h("참가자 필수 실습 3","학년과 주제 입력")}${media("crops/classroom-input-form.png","실제 학년과 주제 입력 양식","저장된 빈 양식 · 입력 예시는 교재 G21","large")}${callout("고등학교 1학년 + 교사의 수업 주제")}`,"양식은 실제 화면이고 빈 상태다. 참가자는 자기 교과 주제를 넣는다.","evidence-slide");
  add("필수 실습 4: 점검","Classroom Gemini","G21",`${h("참가자 필수 실습 4","결과에서 표현 한 곳 점검")}${media("crops/classroom-first-result.png","실제 오개념 첫 생성 결과의 보존된 부분","실제 첫 결과 중 두 항목 · 학교·교과 맥락과 비교","large")}${callout("확인: 학생의 이해를 결과물만으로 단정하지 않았는가?")}`,"전체 결과를 다시 쓰지 않아도 된다. 화면에서 표현 한 문장을 고른다.","evidence-slide");
  add("필수 실습 5: 수정","Classroom Gemini","G21",`${h("참가자 필수 실습 5","교사가 한 문장 수정")}${media("crops/classroom-first-result.png","실제 오개념 결과 화면에서 수정할 표현 찾기","실제 결과를 바탕으로 교사가 문장 수정 · 수정본 UI 캡처는 없음","large")}${callout("수정 예: ‘학생의 설명 가능한 수정 과정과 최종 결과물을 함께 살펴본다.’")}`,"저장된 수정본 UI는 없다. 이전 결과 화면에서 한 문장을 선택하고 수정 전후를 교재에 기록한다.","evidence-slide");

  // H. SenGPT 강사 시연
  add("SenGPT","SenGPT","G22",`${h("SenGPT","교육청 계정의 AI 작업 공간")}${media("sengpt/20260929/home-full.png","SenGPT 전체 첫 화면의 실제 계정 모습","실제 SenGPT 전체 화면 · 2026.9.29.","large")}`,"SEN 홈 도구모음에서 SenGPT로 진입한다. 왼쪽 사용량, 중앙 대화, 아래 서울시교육청 에이전트를 짚는다.","evidence-slide");
  add("SenGPT 모델 선택","SenGPT","G22",`${h("SenGPT","모델 선택 메뉴를 읽는 법")}${screenPanel("sengpt/20260929/models-overview.png","실제 SenGPT 모델 선택 메뉴","실제 SenGPT 계정 화면 · 2026.9.29.",["상단 모델 선택에서 제공 모델을 확인합니다.","같은 서비스 안에서도 모델별 응답 특성이 다릅니다.","에이전트에서 선택한 모델은 Gemini 3.5 Flash Lite입니다."])}`,"실제 모델 선택 목록을 사용한다. 개인 사용량 수치는 계정마다 달라 별도 일반화하지 않는다.","screen-panel-slide");
  add("SenGPT 모델 범위","SenGPT","G22",`${h("SenGPT","모델 메뉴의 실제 선택지")}<div class="sengpt-pair">${media("sengpt/20260929/models-google.png","Google 모델 목록 실제 화면","Google 모델")}${media("sengpt/20260929/models-openai-1.png","OpenAI 모델 목록 실제 화면","OpenAI 모델")}</div>${callout("메뉴에서 보이는 모델을 확인하고, 작업에 맞는 모델을 선택합니다.")}`,"제공 모델은 화면 시점의 실제 메뉴다. 모든 계정에서 동일하거나 영구적으로 고정된 목록이라고 말하지 않는다.","pair-slide");
  add("SenGPT 개인 사용량","SenGPT","G22",`${h("SenGPT","개인 사용량은 계정별로 확인")}<div class="usage-layout"><figure><img src="${asset("sengpt/20260929/usage-tooltip.png")}" alt="지원단 계정에 0원/60,000원과 초기화까지 D-2가 보이는 실제 사용량 툴팁"><figcaption>강사 지원단 계정의 실제 사용량 표시 · 2026.9.29.</figcaption></figure><div><b>강사 시연 계정</b><strong>0원 / 60,000원</strong><p>지원단 계정에서 보인 값입니다.</p><b>일반 계정</b><strong>30,000원 기준</strong><p>참가자는 자신의 화면에서 제공량과 초기화 시점을 확인합니다.</p></div></div>`,"60,000원은 강사의 SEN스쿨 지원단 계정 화면에 실제 표시된 값이다. 일반 사용량 30,000원은 사용자 제공 설명이며 계정·시기에 따른 실제 제공량을 현장에서 다시 확인한다.","usage-slide");
  add("서울시교육청 에이전트 ①","SenGPT","G22",`${h("SenGPT","서울시교육청 에이전트 · 분야별 목록")}<p class="interact-hint">각 화면은 실제 목록입니다. 클릭하면 확대됩니다.</p>${officialGallery(officialAgents.slice(0,4))}`,"연수·성장, 수업·평가·연구, 학생지원·생활, 안전·보호 분야의 실제 화면이다. 에이전트 이름과 설명은 검색 출발점이지 공식 답변의 정확성 보증이 아니다.","official-gallery-slide");
  add("서울시교육청 에이전트 ②","SenGPT","G22",`${h("SenGPT","계약 · 민원 · 공모전 당선작")}<p class="interact-hint">카드를 클릭하면 실제 목록과 화면 설명을 확인할 수 있습니다.</p>${officialGallery(officialAgents.slice(4))}`,"계약·인사, 민원·기관, 공모전 당선작 분야의 실제 화면이다. 활용할 때 연결된 근거 문서를 따로 확인한다.","official-gallery-slide");
  add("나만의 에이전트 목록","SenGPT","G23",`${h("SenGPT","나만의 에이전트에서 만들기")}${screenPanel("sengpt/20260929/agent-list-1.png","나만의 에이전트 목록과 테스트 에이전트","실제 계정 · 저장된 테스트 에이전트 표시",["‘나만의 에이전트’ 탭을 엽니다.","‘에이전트 만들기’로 새 에이전트의 입력 화면에 들어갑니다.","완성된 ‘한영고 연수 테스트 | 수업 질문 도우미’가 목록에 보입니다."])}`,"실제 완료 목록이다. 추가 에이전트를 생성하지 않는다.","screen-panel-slide");
  add("에이전트 만들기 ①","SenGPT","G23",`${h("SenGPT","유형 · 모델 · 이름 · 설명")}${screenPanel("sengpt/20260929/agent-completed-form.png","완성된 테스트 에이전트의 설정 상단","실제 에이전트 수정 화면 · 기존 설정 재확인",["유형은 대화형을 선택했습니다.","모델은 Gemini 3.5 Flash Lite입니다.","이름과 설명을 교사의 수업 질문 작업에 맞게 입력했습니다."])}`,"새 에이전트 생성이 아니라 기존 테스트 에이전트의 실제 수정 화면을 열어 확인한 모습이다.","screen-panel-slide");
  add("에이전트 만들기 ②","SenGPT","G23",`${h("SenGPT","Prompt 작성 도움: 요술봉")}${wizardPanel()}`,"실제 UI에는 별도 기능명이 보이지 않으므로 ‘Prompt 작성 도움’으로 설명한다. 요술봉은 초안을 돕는 버튼이며, 제안 결과를 그대로 확정하지 않는다. 기존 테스트 에이전트의 Prompt 전문과 시작 가이드는 교재 G23에서 확인한다.","screen-panel-slide");
  add("에이전트 도구 설정","SenGPT","G23",`${h("SenGPT","필요한 도구만 선택")}${screenPanel("sengpt/20260929/agent-completed-tools-top.png","에이전트에서 선택 가능한 연결 도구 실제 화면","실제 에이전트 수정 화면 · 연결 도구",["M365·Google Calendar·Notion 등 연결 도구를 확인합니다.","이 테스트 에이전트에서는 도구를 선택하지 않았습니다.","수업 자료와 무관한 권한을 넓히지 않습니다."])}`,"선택지 화면을 보여 줄 뿐, 연결된 계정 내용을 열거나 외부 작업을 실행하지 않는다.","screen-panel-slide");
  add("SenGPT 예약 입력","SenGPT","G24",`${h("SenGPT","에이전트에게 맡길 일 예약")}${screenPanel("sengpt/20260929/schedule-paused-edit.png","일시정지된 테스트 예약의 입력 항목","실제 예약 수정 화면 · 2026.10.05 09:00, 일회성",["대상: ‘한영고 연수 테스트 | 수업 질문 도우미’", "날짜·시간·서울 시간대·한 번만 실행을 확인합니다.","요청문을 쓰고 이메일 결과 수신은 끕니다."])}`,"기존 일시정지 예약의 수정 화면이다. 수정 버튼을 누르지 않고 캡처만 했다.","screen-panel-slide");
  add("SenGPT 예약의 이메일 선택","SenGPT","G24",`${h("SenGPT","결과 메일 수신은 선택 사항")}${screenPanel("sengpt/20260929/schedule-email-on-example.png","다른 예약에서 이메일 수신이 켜진 실제 설정","기존 예약의 실제 수정 화면 · 이메일 수신 켠 예",["체크 해제: 결과 메일을 받지 않습니다.","체크: 수신 주소 입력 칸이 나타납니다.","연수 테스트 ‘수업 준비 점검’은 메일 수신을 껐습니다."])}`,"기존 다른 예약의 실제 설정 예시다. 테스트 예약의 메일 설정과 혼동하지 않는다. 외부 메일을 새로 발송하지 않는다.","screen-panel-slide");
  add("예약 저장과 비활성화","SenGPT","G24",`${h("SenGPT","저장된 예약의 일시정지 상태")}${screenPanel("sengpt/20260929/schedule-paused-list.png","수업 준비 점검 예약이 일시정지된 실제 목록","실제 예약 목록 · 일회성 / 일시정지",["목록에 ‘수업 준비 점검’이 저장되어 있습니다.","‘일시정지’ 표시와 꺼진 스위치를 확인합니다.","현재 상태를 유지하고 다시 켜지 않습니다."])}`,"사용자가 제공한 실제 예약 목록 캡처다. 예약은 비활성화 상태를 유지한다.","screen-panel-slide");
  add("SenGPT 선택 따라하기","SenGPT","G25",`${h("시간이 허용되면","에이전트·예약 선택 따라하기")}<div class="plain-row"><div>강사 화면의 입력 항목을 따라봅니다.</div><div>민감자료·외부 파일·메일 결과 수신은 사용하지 않습니다.</div><div>시간이 부족하면 강사 시연까지만 봅니다.</div></div>`,"Classroom Gemini 필수 실습 시간을 줄이지 않는다. SenGPT 참가자 조작은 선택이다.");

  // I. 정리
  add("정리와 다시 시작","마무리","G26",`${h("연수 후","교재에서 다시 시작하기")}<div class="closing-map"><div><b>SEN스쿨</b><span>기능과 공식 절차</span></div><div><b>Notebook</b><span>강사 시연 복습·자율 실습</span></div><div><b>Classroom</b><span>오개념 한 문장 수정</span></div><div><b>SenGPT</b><span>에이전트·예약 절차</span></div></div>${callout("참가자 교재의 원문 링크·Prompt·실제 화면을 연수 후 참고하세요.")}`,"시간이 남으면 질문을 받고 교재의 해당 절로 바로 이동한다.");

  window.DECK = deck;
})();
